apiVersion: v1
kind: ReplicationController
metadata:
  name: blue
  labels:
    app: nginxyblue
spec:
  replicas: 1
  selector:
    app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: imyke/nginxy