version: 2.1

jobs:
  build-and-lint:
    docker:
      -image: circleci/python
    steps:
      - checkout
      - run:
          command: |
            make setup
            make lint
            make build
            make run

workflows:
  main:
    jobs:
      - build-and-lint
