version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          command: |
            make setup
            make build
            make run
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run make lint

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
